---
- hosts: all
  connection: ssh
  become: yes
  become_method: sudo
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: installed

    
    - name: Start Apache
      service:
        name: httpd
        state: started
        
   
    - name: Install MySql and PHP
      yum: 
        name: "{{item}}"
        state: installed
      with_items: 

        - mysql-server
        - php-mysql

    - name: Start MySQL
      service:
        name: mysqld
        state: started
        
